api_authentication_check:
  path: /api/authentication_check
  controller: App\Controller\AuthController::getTokenUser

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST