api_authentication_check:
  path: /api/authentication
  controller: App\Controller\AuthController::getTokenUser

register:
  path: /api/register
  controller: App\Controller\AuthController::register
  methods: POST